/**
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.farmbot.MyFarmbotRuntimeModule;
import xtext.farmbot.MyFarmbotStandaloneSetup;
import xtext.farmbot.ide.MyFarmbotIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyFarmbotIdeSetup extends MyFarmbotStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyFarmbotRuntimeModule _myFarmbotRuntimeModule = new MyFarmbotRuntimeModule();
    MyFarmbotIdeModule _myFarmbotIdeModule = new MyFarmbotIdeModule();
    return Guice.createInjector(Modules2.mixin(_myFarmbotRuntimeModule, _myFarmbotIdeModule));
  }
}
