/**
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ide;

import xtext.farmbot.ide.AbstractMyFarmbotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyFarmbotIdeModule extends AbstractMyFarmbotIdeModule {
}
