/**
 * generated by Xtext 2.15.0
 */
package xtext.farmbot;

import xtext.farmbot.AbstractMyFarmbotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyFarmbotRuntimeModule extends AbstractMyFarmbotRuntimeModule {
}
