/**
 * generated by Xtext 2.15.0
 */
package xtext.farmbot;

import xtext.farmbot.MyFarmbotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyFarmbotStandaloneSetup extends MyFarmbotStandaloneSetupGenerated {
  public static void doSetup() {
    new MyFarmbotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
