/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyFarmbotGrammarAccess extends AbstractGrammarElementFinder {
	
	public class FarmbotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.Farmbot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFarmbotAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cInstructionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInstructionsInstructionParserRuleCall_1_0 = (RuleCall)cInstructionsAssignment_1.eContents().get(0);
		
		//Farmbot:
		//	{Farmbot} instructions+=Instruction+;
		@Override public ParserRule getRule() { return rule; }
		
		//{Farmbot} instructions+=Instruction+
		public Group getGroup() { return cGroup; }
		
		//{Farmbot}
		public Action getFarmbotAction_0() { return cFarmbotAction_0; }
		
		//instructions+=Instruction+
		public Assignment getInstructionsAssignment_1() { return cInstructionsAssignment_1; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_1_0() { return cInstructionsInstructionParserRuleCall_1_0; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSequenceInstructionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSequenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCommandParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Instruction:
		//	SequenceInstruction | Sequence | Command;
		@Override public ParserRule getRule() { return rule; }
		
		//SequenceInstruction | Sequence | Command
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SequenceInstruction
		public RuleCall getSequenceInstructionParserRuleCall_0() { return cSequenceInstructionParserRuleCall_0; }
		
		//Sequence
		public RuleCall getSequenceParserRuleCall_1() { return cSequenceParserRuleCall_1; }
		
		//Command
		public RuleCall getCommandParserRuleCall_2() { return cCommandParserRuleCall_2; }
	}
	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cScheduleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cListPeripheralsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cListSequencesParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Command:
		//	Schedule | ListPeripherals | ListSequences;
		@Override public ParserRule getRule() { return rule; }
		
		//Schedule | ListPeripherals | ListSequences
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Schedule
		public RuleCall getScheduleParserRuleCall_0() { return cScheduleParserRuleCall_0; }
		
		//ListPeripherals
		public RuleCall getListPeripheralsParserRuleCall_1() { return cListPeripheralsParserRuleCall_1; }
		
		//ListSequences
		public RuleCall getListSequencesParserRuleCall_2() { return cListSequencesParserRuleCall_2; }
	}
	public class SequenceCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.SequenceCommand");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTurnOnParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTurnOffParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMoveRelativeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFindHomeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cMoveAbsoluteParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cExecuteSequenceParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cWaitParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cIsToolOnParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cSendMessageParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cRunFarmwareParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cTakePhotoParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		
		//SequenceCommand:
		//	TurnOn | TurnOff | MoveRelative | FindHome | MoveAbsolute | ExecuteSequence | Wait | IsToolOn | SendMessage |
		//	RunFarmware | TakePhoto;
		@Override public ParserRule getRule() { return rule; }
		
		//TurnOn | TurnOff | MoveRelative | FindHome | MoveAbsolute | ExecuteSequence | Wait | IsToolOn | SendMessage |
		//RunFarmware | TakePhoto
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TurnOn
		public RuleCall getTurnOnParserRuleCall_0() { return cTurnOnParserRuleCall_0; }
		
		//TurnOff
		public RuleCall getTurnOffParserRuleCall_1() { return cTurnOffParserRuleCall_1; }
		
		//MoveRelative
		public RuleCall getMoveRelativeParserRuleCall_2() { return cMoveRelativeParserRuleCall_2; }
		
		//FindHome
		public RuleCall getFindHomeParserRuleCall_3() { return cFindHomeParserRuleCall_3; }
		
		//MoveAbsolute
		public RuleCall getMoveAbsoluteParserRuleCall_4() { return cMoveAbsoluteParserRuleCall_4; }
		
		//ExecuteSequence
		public RuleCall getExecuteSequenceParserRuleCall_5() { return cExecuteSequenceParserRuleCall_5; }
		
		//Wait
		public RuleCall getWaitParserRuleCall_6() { return cWaitParserRuleCall_6; }
		
		//IsToolOn
		public RuleCall getIsToolOnParserRuleCall_7() { return cIsToolOnParserRuleCall_7; }
		
		//SendMessage
		public RuleCall getSendMessageParserRuleCall_8() { return cSendMessageParserRuleCall_8; }
		
		//RunFarmware
		public RuleCall getRunFarmwareParserRuleCall_9() { return cRunFarmwareParserRuleCall_9; }
		
		//TakePhoto
		public RuleCall getTakePhotoParserRuleCall_10() { return cTakePhotoParserRuleCall_10; }
	}
	public class SequenceInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.SequenceInstruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIfParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSequenceCommandParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//SequenceInstruction:
		//	If | SequenceCommand;
		@Override public ParserRule getRule() { return rule; }
		
		//If | SequenceCommand
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//If
		public RuleCall getIfParserRuleCall_0() { return cIfParserRuleCall_0; }
		
		//SequenceCommand
		public RuleCall getSequenceCommandParserRuleCall_1() { return cSequenceCommandParserRuleCall_1; }
	}
	public class BooleanExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.BooleanExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIsToolOnParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIsEqualToParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIsNotEqualToParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cIsGreaterThanParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cIsLowerThanParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//BooleanExpression:
		//	IsToolOn | IsEqualTo | IsNotEqualTo | IsGreaterThan | IsLowerThan;
		@Override public ParserRule getRule() { return rule; }
		
		//IsToolOn | IsEqualTo | IsNotEqualTo | IsGreaterThan | IsLowerThan
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IsToolOn
		public RuleCall getIsToolOnParserRuleCall_0() { return cIsToolOnParserRuleCall_0; }
		
		//IsEqualTo
		public RuleCall getIsEqualToParserRuleCall_1() { return cIsEqualToParserRuleCall_1; }
		
		//IsNotEqualTo
		public RuleCall getIsNotEqualToParserRuleCall_2() { return cIsNotEqualToParserRuleCall_2; }
		
		//IsGreaterThan
		public RuleCall getIsGreaterThanParserRuleCall_3() { return cIsGreaterThanParserRuleCall_3; }
		
		//IsLowerThan
		public RuleCall getIsLowerThanParserRuleCall_4() { return cIsLowerThanParserRuleCall_4; }
	}
	public class TurnOnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.TurnOn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTurnOnAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTurnOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPinKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPinAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPinINTTerminalRuleCall_3_0 = (RuleCall)cPinAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cModeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cModeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cModeSTRINGTerminalRuleCall_6_0 = (RuleCall)cModeAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//TurnOn:
		//	{TurnOn}
		//	'turnOn(' 'pin=' pin=INT ',' 'mode=' mode=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{TurnOn} 'turnOn(' 'pin=' pin=INT ',' 'mode=' mode=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{TurnOn}
		public Action getTurnOnAction_0() { return cTurnOnAction_0; }
		
		//'turnOn('
		public Keyword getTurnOnKeyword_1() { return cTurnOnKeyword_1; }
		
		//'pin='
		public Keyword getPinKeyword_2() { return cPinKeyword_2; }
		
		//pin=INT
		public Assignment getPinAssignment_3() { return cPinAssignment_3; }
		
		//INT
		public RuleCall getPinINTTerminalRuleCall_3_0() { return cPinINTTerminalRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'mode='
		public Keyword getModeKeyword_5() { return cModeKeyword_5; }
		
		//mode=STRING
		public Assignment getModeAssignment_6() { return cModeAssignment_6; }
		
		//STRING
		public RuleCall getModeSTRINGTerminalRuleCall_6_0() { return cModeSTRINGTerminalRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class TurnOffElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.TurnOff");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTurnOffAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTurnOffKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPinKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPinAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPinINTTerminalRuleCall_3_0 = (RuleCall)cPinAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cModeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cModeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cModeSTRINGTerminalRuleCall_6_0 = (RuleCall)cModeAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//TurnOff:
		//	{TurnOff}
		//	'turnOff(' 'pin=' pin=INT ',' 'mode=' mode=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{TurnOff} 'turnOff(' 'pin=' pin=INT ',' 'mode=' mode=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{TurnOff}
		public Action getTurnOffAction_0() { return cTurnOffAction_0; }
		
		//'turnOff('
		public Keyword getTurnOffKeyword_1() { return cTurnOffKeyword_1; }
		
		//'pin='
		public Keyword getPinKeyword_2() { return cPinKeyword_2; }
		
		//pin=INT
		public Assignment getPinAssignment_3() { return cPinAssignment_3; }
		
		//INT
		public RuleCall getPinINTTerminalRuleCall_3_0() { return cPinINTTerminalRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'mode='
		public Keyword getModeKeyword_5() { return cModeKeyword_5; }
		
		//mode=STRING
		public Assignment getModeAssignment_6() { return cModeAssignment_6; }
		
		//STRING
		public RuleCall getModeSTRINGTerminalRuleCall_6_0() { return cModeSTRINGTerminalRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class MoveRelativeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.MoveRelative");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveRelativeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMoveRelativeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cXINTTerminalRuleCall_3_0 = (RuleCall)cXAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cYKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYINTTerminalRuleCall_6_0 = (RuleCall)cYAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cZKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cZAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cZINTTerminalRuleCall_9_0 = (RuleCall)cZAssignment_9.eContents().get(0);
		private final Keyword cCommaKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cSpeedKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cSpeedAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cSpeedEDoubleParserRuleCall_12_0 = (RuleCall)cSpeedAssignment_12.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//MoveRelative:
		//	{MoveRelative}
		//	'moveRelative(' 'x=' x=INT ',' 'y=' y=INT ',' 'z=' z=INT ',' 'speed=' speed=EDouble ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveRelative} 'moveRelative(' 'x=' x=INT ',' 'y=' y=INT ',' 'z=' z=INT ',' 'speed=' speed=EDouble ')'
		public Group getGroup() { return cGroup; }
		
		//{MoveRelative}
		public Action getMoveRelativeAction_0() { return cMoveRelativeAction_0; }
		
		//'moveRelative('
		public Keyword getMoveRelativeKeyword_1() { return cMoveRelativeKeyword_1; }
		
		//'x='
		public Keyword getXKeyword_2() { return cXKeyword_2; }
		
		//x=INT
		public Assignment getXAssignment_3() { return cXAssignment_3; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_3_0() { return cXINTTerminalRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'y='
		public Keyword getYKeyword_5() { return cYKeyword_5; }
		
		//y=INT
		public Assignment getYAssignment_6() { return cYAssignment_6; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_6_0() { return cYINTTerminalRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//'z='
		public Keyword getZKeyword_8() { return cZKeyword_8; }
		
		//z=INT
		public Assignment getZAssignment_9() { return cZAssignment_9; }
		
		//INT
		public RuleCall getZINTTerminalRuleCall_9_0() { return cZINTTerminalRuleCall_9_0; }
		
		//','
		public Keyword getCommaKeyword_10() { return cCommaKeyword_10; }
		
		//'speed='
		public Keyword getSpeedKeyword_11() { return cSpeedKeyword_11; }
		
		//speed=EDouble
		public Assignment getSpeedAssignment_12() { return cSpeedAssignment_12; }
		
		//EDouble
		public RuleCall getSpeedEDoubleParserRuleCall_12_0() { return cSpeedEDoubleParserRuleCall_12_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_13() { return cRightParenthesisKeyword_13; }
	}
	public class FindHomeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.FindHome");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFindHomeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFindHomeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFindXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFindXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFindXEBooleanParserRuleCall_3_0 = (RuleCall)cFindXAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cFindYKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFindYAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFindYEBooleanParserRuleCall_6_0 = (RuleCall)cFindYAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cFindZKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFindZAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFindZEBooleanParserRuleCall_9_0 = (RuleCall)cFindZAssignment_9.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//FindHome:
		//	{FindHome}
		//	'findHome(' 'findX=' findX=EBoolean ',' 'findY=' findY=EBoolean ',' 'findZ=' findZ=EBoolean ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{FindHome} 'findHome(' 'findX=' findX=EBoolean ',' 'findY=' findY=EBoolean ',' 'findZ=' findZ=EBoolean ')'
		public Group getGroup() { return cGroup; }
		
		//{FindHome}
		public Action getFindHomeAction_0() { return cFindHomeAction_0; }
		
		//'findHome('
		public Keyword getFindHomeKeyword_1() { return cFindHomeKeyword_1; }
		
		//'findX='
		public Keyword getFindXKeyword_2() { return cFindXKeyword_2; }
		
		//findX=EBoolean
		public Assignment getFindXAssignment_3() { return cFindXAssignment_3; }
		
		//EBoolean
		public RuleCall getFindXEBooleanParserRuleCall_3_0() { return cFindXEBooleanParserRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'findY='
		public Keyword getFindYKeyword_5() { return cFindYKeyword_5; }
		
		//findY=EBoolean
		public Assignment getFindYAssignment_6() { return cFindYAssignment_6; }
		
		//EBoolean
		public RuleCall getFindYEBooleanParserRuleCall_6_0() { return cFindYEBooleanParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//'findZ='
		public Keyword getFindZKeyword_8() { return cFindZKeyword_8; }
		
		//findZ=EBoolean
		public Assignment getFindZAssignment_9() { return cFindZAssignment_9; }
		
		//EBoolean
		public RuleCall getFindZEBooleanParserRuleCall_9_0() { return cFindZEBooleanParserRuleCall_9_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10() { return cRightParenthesisKeyword_10; }
	}
	public class SequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.Sequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSequenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSequenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cSequenceInstructionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSequenceInstructionsSequenceInstructionParserRuleCall_3_0 = (RuleCall)cSequenceInstructionsAssignment_3.eContents().get(0);
		private final Keyword cEndKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Sequence:
		//	{Sequence}
		//	'sequence' name=STRING
		//	sequenceInstructions+=SequenceInstruction*
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//{Sequence} 'sequence' name=STRING sequenceInstructions+=SequenceInstruction* 'end'
		public Group getGroup() { return cGroup; }
		
		//{Sequence}
		public Action getSequenceAction_0() { return cSequenceAction_0; }
		
		//'sequence'
		public Keyword getSequenceKeyword_1() { return cSequenceKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//sequenceInstructions+=SequenceInstruction*
		public Assignment getSequenceInstructionsAssignment_3() { return cSequenceInstructionsAssignment_3; }
		
		//SequenceInstruction
		public RuleCall getSequenceInstructionsSequenceInstructionParserRuleCall_3_0() { return cSequenceInstructionsSequenceInstructionParserRuleCall_3_0; }
		
		//'end'
		public Keyword getEndKeyword_4() { return cEndKeyword_4; }
	}
	public class IfElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.If");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIfAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIfKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cBooleanExpressionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBooleanExpressionBooleanExpressionParserRuleCall_2_0 = (RuleCall)cBooleanExpressionAssignment_2.eContents().get(0);
		private final Keyword cThenKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cThenAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cThenExecuteSequenceParserRuleCall_4_0 = (RuleCall)cThenAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cElseKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cElseAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cElseExecuteSequenceParserRuleCall_5_1_0 = (RuleCall)cElseAssignment_5_1.eContents().get(0);
		private final Keyword cEndKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//If:
		//	{If}
		//	'if' booleanExpression=BooleanExpression
		//	'then' then=ExecuteSequence ('else' else=ExecuteSequence)?
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//{If} 'if' booleanExpression=BooleanExpression 'then' then=ExecuteSequence ('else' else=ExecuteSequence)? 'end'
		public Group getGroup() { return cGroup; }
		
		//{If}
		public Action getIfAction_0() { return cIfAction_0; }
		
		//'if'
		public Keyword getIfKeyword_1() { return cIfKeyword_1; }
		
		//booleanExpression=BooleanExpression
		public Assignment getBooleanExpressionAssignment_2() { return cBooleanExpressionAssignment_2; }
		
		//BooleanExpression
		public RuleCall getBooleanExpressionBooleanExpressionParserRuleCall_2_0() { return cBooleanExpressionBooleanExpressionParserRuleCall_2_0; }
		
		//'then'
		public Keyword getThenKeyword_3() { return cThenKeyword_3; }
		
		//then=ExecuteSequence
		public Assignment getThenAssignment_4() { return cThenAssignment_4; }
		
		//ExecuteSequence
		public RuleCall getThenExecuteSequenceParserRuleCall_4_0() { return cThenExecuteSequenceParserRuleCall_4_0; }
		
		//('else' else=ExecuteSequence)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'else'
		public Keyword getElseKeyword_5_0() { return cElseKeyword_5_0; }
		
		//else=ExecuteSequence
		public Assignment getElseAssignment_5_1() { return cElseAssignment_5_1; }
		
		//ExecuteSequence
		public RuleCall getElseExecuteSequenceParserRuleCall_5_1_0() { return cElseExecuteSequenceParserRuleCall_5_1_0; }
		
		//'end'
		public Keyword getEndKeyword_6() { return cEndKeyword_6; }
	}
	public class MoveAbsoluteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.MoveAbsolute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveAbsoluteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMoveAbsoluteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cXINTTerminalRuleCall_3_0 = (RuleCall)cXAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cYKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYINTTerminalRuleCall_6_0 = (RuleCall)cYAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cZKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cZAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cZINTTerminalRuleCall_9_0 = (RuleCall)cZAssignment_9.eContents().get(0);
		private final Keyword cCommaKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cSpeedKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cSpeedAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cSpeedEDoubleParserRuleCall_12_0 = (RuleCall)cSpeedAssignment_12.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//MoveAbsolute:
		//	{MoveAbsolute}
		//	'moveAbsolute(' 'x=' x=INT ',' 'y=' y=INT ',' 'z=' z=INT ',' 'speed=' speed=EDouble ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveAbsolute} 'moveAbsolute(' 'x=' x=INT ',' 'y=' y=INT ',' 'z=' z=INT ',' 'speed=' speed=EDouble ')'
		public Group getGroup() { return cGroup; }
		
		//{MoveAbsolute}
		public Action getMoveAbsoluteAction_0() { return cMoveAbsoluteAction_0; }
		
		//'moveAbsolute('
		public Keyword getMoveAbsoluteKeyword_1() { return cMoveAbsoluteKeyword_1; }
		
		//'x='
		public Keyword getXKeyword_2() { return cXKeyword_2; }
		
		//x=INT
		public Assignment getXAssignment_3() { return cXAssignment_3; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_3_0() { return cXINTTerminalRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'y='
		public Keyword getYKeyword_5() { return cYKeyword_5; }
		
		//y=INT
		public Assignment getYAssignment_6() { return cYAssignment_6; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_6_0() { return cYINTTerminalRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//'z='
		public Keyword getZKeyword_8() { return cZKeyword_8; }
		
		//z=INT
		public Assignment getZAssignment_9() { return cZAssignment_9; }
		
		//INT
		public RuleCall getZINTTerminalRuleCall_9_0() { return cZINTTerminalRuleCall_9_0; }
		
		//','
		public Keyword getCommaKeyword_10() { return cCommaKeyword_10; }
		
		//'speed='
		public Keyword getSpeedKeyword_11() { return cSpeedKeyword_11; }
		
		//speed=EDouble
		public Assignment getSpeedAssignment_12() { return cSpeedAssignment_12; }
		
		//EDouble
		public RuleCall getSpeedEDoubleParserRuleCall_12_0() { return cSpeedEDoubleParserRuleCall_12_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_13() { return cRightParenthesisKeyword_13; }
	}
	public class ExecuteSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.ExecuteSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExecuteSequenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExecuteSequenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIdAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIdINTTerminalRuleCall_4_0 = (RuleCall)cIdAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ExecuteSequence:
		//	{ExecuteSequence}
		//	'executeSequence' '(' 'id=' id=INT ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{ExecuteSequence} 'executeSequence' '(' 'id=' id=INT ')'
		public Group getGroup() { return cGroup; }
		
		//{ExecuteSequence}
		public Action getExecuteSequenceAction_0() { return cExecuteSequenceAction_0; }
		
		//'executeSequence'
		public Keyword getExecuteSequenceKeyword_1() { return cExecuteSequenceKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'id='
		public Keyword getIdKeyword_3() { return cIdKeyword_3; }
		
		//id=INT
		public Assignment getIdAssignment_4() { return cIdAssignment_4; }
		
		//INT
		public RuleCall getIdINTTerminalRuleCall_4_0() { return cIdINTTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class WaitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.Wait");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWaitAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWaitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDurationKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDurationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDurationEDoubleParserRuleCall_4_0 = (RuleCall)cDurationAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Wait:
		//	{Wait}
		//	'wait' '(' 'duration=' duration=EDouble ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{Wait} 'wait' '(' 'duration=' duration=EDouble ')'
		public Group getGroup() { return cGroup; }
		
		//{Wait}
		public Action getWaitAction_0() { return cWaitAction_0; }
		
		//'wait'
		public Keyword getWaitKeyword_1() { return cWaitKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'duration='
		public Keyword getDurationKeyword_3() { return cDurationKeyword_3; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_4() { return cDurationAssignment_4; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_4_0() { return cDurationEDoubleParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class IsToolOnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.IsToolOn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIsToolOnAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIsToolOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPinKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPinAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPinINTTerminalRuleCall_4_0 = (RuleCall)cPinAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//IsToolOn:
		//	{IsToolOn}
		//	'isToolOn' '(' 'pin=' pin=INT ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{IsToolOn} 'isToolOn' '(' 'pin=' pin=INT ')'
		public Group getGroup() { return cGroup; }
		
		//{IsToolOn}
		public Action getIsToolOnAction_0() { return cIsToolOnAction_0; }
		
		//'isToolOn'
		public Keyword getIsToolOnKeyword_1() { return cIsToolOnKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'pin='
		public Keyword getPinKeyword_3() { return cPinKeyword_3; }
		
		//pin=INT
		public Assignment getPinAssignment_4() { return cPinAssignment_4; }
		
		//INT
		public RuleCall getPinINTTerminalRuleCall_4_0() { return cPinINTTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class SendMessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.SendMessage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSendMessageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSendMessageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMessageKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMessageAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMessageSTRINGTerminalRuleCall_4_0 = (RuleCall)cMessageAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SendMessage:
		//	{SendMessage}
		//	'sendMessage' '(' 'message=' message=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{SendMessage} 'sendMessage' '(' 'message=' message=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{SendMessage}
		public Action getSendMessageAction_0() { return cSendMessageAction_0; }
		
		//'sendMessage'
		public Keyword getSendMessageKeyword_1() { return cSendMessageKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'message='
		public Keyword getMessageKeyword_3() { return cMessageKeyword_3; }
		
		//message=STRING
		public Assignment getMessageAssignment_4() { return cMessageAssignment_4; }
		
		//STRING
		public RuleCall getMessageSTRINGTerminalRuleCall_4_0() { return cMessageSTRINGTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class RunFarmwareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.RunFarmware");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRunFarmwareAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRunFarmwareKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RunFarmware:
		//	{RunFarmware}
		//	'runFarmware' '(' 'name=' name=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{RunFarmware} 'runFarmware' '(' 'name=' name=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{RunFarmware}
		public Action getRunFarmwareAction_0() { return cRunFarmwareAction_0; }
		
		//'runFarmware'
		public Keyword getRunFarmwareKeyword_1() { return cRunFarmwareKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'name='
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//name=STRING
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_4_0() { return cNameSTRINGTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class TakePhotoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.TakePhoto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTakePhotoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTakePhotoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//TakePhoto:
		//	{TakePhoto}
		//	'takePhoto()';
		@Override public ParserRule getRule() { return rule; }
		
		//{TakePhoto} 'takePhoto()'
		public Group getGroup() { return cGroup; }
		
		//{TakePhoto}
		public Action getTakePhotoAction_0() { return cTakePhotoAction_0; }
		
		//'takePhoto()'
		public Keyword getTakePhotoKeyword_1() { return cTakePhotoKeyword_1; }
	}
	public class ScheduleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.Schedule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cScheduleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cScheduleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSequenceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSequenceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSequenceSTRINGTerminalRuleCall_4_0 = (RuleCall)cSequenceAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cStartDateKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStartDateAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStartDateSTRINGTerminalRuleCall_7_0 = (RuleCall)cStartDateAssignment_7.eContents().get(0);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cStartTimeKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cStartTimeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cStartTimeSTRINGTerminalRuleCall_10_0 = (RuleCall)cStartTimeAssignment_10.eContents().get(0);
		private final Keyword cCommaKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRepeatKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cRepeatAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cRepeatEBooleanParserRuleCall_13_0 = (RuleCall)cRepeatAssignment_13.eContents().get(0);
		private final Keyword cCommaKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRepeatFrequencyKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cRepeatFrequencyAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cRepeatFrequencyINTTerminalRuleCall_16_0 = (RuleCall)cRepeatFrequencyAssignment_16.eContents().get(0);
		private final Keyword cCommaKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cRepeatUnitKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cRepeatUnitAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cRepeatUnitSTRINGTerminalRuleCall_19_0 = (RuleCall)cRepeatUnitAssignment_19.eContents().get(0);
		private final Keyword cCommaKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cEndDateKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cEndDateAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cEndDateSTRINGTerminalRuleCall_22_0 = (RuleCall)cEndDateAssignment_22.eContents().get(0);
		private final Keyword cCommaKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cEndTimeKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Assignment cEndTimeAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cEndTimeSTRINGTerminalRuleCall_25_0 = (RuleCall)cEndTimeAssignment_25.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_26 = (Keyword)cGroup.eContents().get(26);
		
		//Schedule:
		//	{Schedule}
		//	'schedule' '(' 'sequence=' sequence=STRING ',' 'startDate=' startDate=STRING ',' 'startTime=' startTime=STRING ','
		//	'repeat=' repeat=EBoolean ',' 'repeatFrequency=' repeatFrequency=INT ',' 'repeatUnit=' repeatUnit=STRING ','
		//	'endDate=' endDate=STRING ',' 'endTime=' endTime=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{Schedule} 'schedule' '(' 'sequence=' sequence=STRING ',' 'startDate=' startDate=STRING ',' 'startTime='
		//startTime=STRING ',' 'repeat=' repeat=EBoolean ',' 'repeatFrequency=' repeatFrequency=INT ',' 'repeatUnit='
		//repeatUnit=STRING ',' 'endDate=' endDate=STRING ',' 'endTime=' endTime=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{Schedule}
		public Action getScheduleAction_0() { return cScheduleAction_0; }
		
		//'schedule'
		public Keyword getScheduleKeyword_1() { return cScheduleKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'sequence='
		public Keyword getSequenceKeyword_3() { return cSequenceKeyword_3; }
		
		//sequence=STRING
		public Assignment getSequenceAssignment_4() { return cSequenceAssignment_4; }
		
		//STRING
		public RuleCall getSequenceSTRINGTerminalRuleCall_4_0() { return cSequenceSTRINGTerminalRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//'startDate='
		public Keyword getStartDateKeyword_6() { return cStartDateKeyword_6; }
		
		//startDate=STRING
		public Assignment getStartDateAssignment_7() { return cStartDateAssignment_7; }
		
		//STRING
		public RuleCall getStartDateSTRINGTerminalRuleCall_7_0() { return cStartDateSTRINGTerminalRuleCall_7_0; }
		
		//','
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//'startTime='
		public Keyword getStartTimeKeyword_9() { return cStartTimeKeyword_9; }
		
		//startTime=STRING
		public Assignment getStartTimeAssignment_10() { return cStartTimeAssignment_10; }
		
		//STRING
		public RuleCall getStartTimeSTRINGTerminalRuleCall_10_0() { return cStartTimeSTRINGTerminalRuleCall_10_0; }
		
		//','
		public Keyword getCommaKeyword_11() { return cCommaKeyword_11; }
		
		//'repeat='
		public Keyword getRepeatKeyword_12() { return cRepeatKeyword_12; }
		
		//repeat=EBoolean
		public Assignment getRepeatAssignment_13() { return cRepeatAssignment_13; }
		
		//EBoolean
		public RuleCall getRepeatEBooleanParserRuleCall_13_0() { return cRepeatEBooleanParserRuleCall_13_0; }
		
		//','
		public Keyword getCommaKeyword_14() { return cCommaKeyword_14; }
		
		//'repeatFrequency='
		public Keyword getRepeatFrequencyKeyword_15() { return cRepeatFrequencyKeyword_15; }
		
		//repeatFrequency=INT
		public Assignment getRepeatFrequencyAssignment_16() { return cRepeatFrequencyAssignment_16; }
		
		//INT
		public RuleCall getRepeatFrequencyINTTerminalRuleCall_16_0() { return cRepeatFrequencyINTTerminalRuleCall_16_0; }
		
		//','
		public Keyword getCommaKeyword_17() { return cCommaKeyword_17; }
		
		//'repeatUnit='
		public Keyword getRepeatUnitKeyword_18() { return cRepeatUnitKeyword_18; }
		
		//repeatUnit=STRING
		public Assignment getRepeatUnitAssignment_19() { return cRepeatUnitAssignment_19; }
		
		//STRING
		public RuleCall getRepeatUnitSTRINGTerminalRuleCall_19_0() { return cRepeatUnitSTRINGTerminalRuleCall_19_0; }
		
		//','
		public Keyword getCommaKeyword_20() { return cCommaKeyword_20; }
		
		//'endDate='
		public Keyword getEndDateKeyword_21() { return cEndDateKeyword_21; }
		
		//endDate=STRING
		public Assignment getEndDateAssignment_22() { return cEndDateAssignment_22; }
		
		//STRING
		public RuleCall getEndDateSTRINGTerminalRuleCall_22_0() { return cEndDateSTRINGTerminalRuleCall_22_0; }
		
		//','
		public Keyword getCommaKeyword_23() { return cCommaKeyword_23; }
		
		//'endTime='
		public Keyword getEndTimeKeyword_24() { return cEndTimeKeyword_24; }
		
		//endTime=STRING
		public Assignment getEndTimeAssignment_25() { return cEndTimeAssignment_25; }
		
		//STRING
		public RuleCall getEndTimeSTRINGTerminalRuleCall_25_0() { return cEndTimeSTRINGTerminalRuleCall_25_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_26() { return cRightParenthesisKeyword_26; }
	}
	public class ListPeripheralsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.ListPeripherals");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cListPeripheralsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cListPeripheralsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ListPeripherals:
		//	{ListPeripherals}
		//	'listPeripherals()';
		@Override public ParserRule getRule() { return rule; }
		
		//{ListPeripherals} 'listPeripherals()'
		public Group getGroup() { return cGroup; }
		
		//{ListPeripherals}
		public Action getListPeripheralsAction_0() { return cListPeripheralsAction_0; }
		
		//'listPeripherals()'
		public Keyword getListPeripheralsKeyword_1() { return cListPeripheralsKeyword_1; }
	}
	public class ListSequencesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.ListSequences");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cListSequencesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cListSequencesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ListSequences:
		//	{ListSequences}
		//	'listSequences()';
		@Override public ParserRule getRule() { return rule; }
		
		//{ListSequences} 'listSequences()'
		public Group getGroup() { return cGroup; }
		
		//{ListSequences}
		public Action getListSequencesAction_0() { return cListSequencesAction_0; }
		
		//'listSequences()'
		public Keyword getListSequencesKeyword_1() { return cListSequencesKeyword_1; }
	}
	public class IsEqualToElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.IsEqualTo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIsEqualToAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAxeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAxeSTRINGTerminalRuleCall_1_0 = (RuleCall)cAxeAssignment_1.eContents().get(0);
		private final Keyword cEqualsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueINTTerminalRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//IsEqualTo:
		//	{IsEqualTo} axe=STRING 'equals' 'to' value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//{IsEqualTo} axe=STRING 'equals' 'to' value=INT
		public Group getGroup() { return cGroup; }
		
		//{IsEqualTo}
		public Action getIsEqualToAction_0() { return cIsEqualToAction_0; }
		
		//axe=STRING
		public Assignment getAxeAssignment_1() { return cAxeAssignment_1; }
		
		//STRING
		public RuleCall getAxeSTRINGTerminalRuleCall_1_0() { return cAxeSTRINGTerminalRuleCall_1_0; }
		
		//'equals'
		public Keyword getEqualsKeyword_2() { return cEqualsKeyword_2; }
		
		//'to'
		public Keyword getToKeyword_3() { return cToKeyword_3; }
		
		//value=INT
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_4_0() { return cValueINTTerminalRuleCall_4_0; }
	}
	public class IsNotEqualToElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.IsNotEqualTo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIsNotEqualToAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAxeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAxeSTRINGTerminalRuleCall_1_0 = (RuleCall)cAxeAssignment_1.eContents().get(0);
		private final Keyword cNotKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueINTTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		
		//IsNotEqualTo:
		//	{IsNotEqualTo} axe=STRING 'not' 'equals' 'to' value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//{IsNotEqualTo} axe=STRING 'not' 'equals' 'to' value=INT
		public Group getGroup() { return cGroup; }
		
		//{IsNotEqualTo}
		public Action getIsNotEqualToAction_0() { return cIsNotEqualToAction_0; }
		
		//axe=STRING
		public Assignment getAxeAssignment_1() { return cAxeAssignment_1; }
		
		//STRING
		public RuleCall getAxeSTRINGTerminalRuleCall_1_0() { return cAxeSTRINGTerminalRuleCall_1_0; }
		
		//'not'
		public Keyword getNotKeyword_2() { return cNotKeyword_2; }
		
		//'equals'
		public Keyword getEqualsKeyword_3() { return cEqualsKeyword_3; }
		
		//'to'
		public Keyword getToKeyword_4() { return cToKeyword_4; }
		
		//value=INT
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_5_0() { return cValueINTTerminalRuleCall_5_0; }
	}
	public class IsGreaterThanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.IsGreaterThan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIsGreaterThanAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAxeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAxeSTRINGTerminalRuleCall_1_0 = (RuleCall)cAxeAssignment_1.eContents().get(0);
		private final Keyword cGreaterKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cThanKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueINTTerminalRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//IsGreaterThan:
		//	{IsGreaterThan} axe=STRING 'greater' 'than' value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//{IsGreaterThan} axe=STRING 'greater' 'than' value=INT
		public Group getGroup() { return cGroup; }
		
		//{IsGreaterThan}
		public Action getIsGreaterThanAction_0() { return cIsGreaterThanAction_0; }
		
		//axe=STRING
		public Assignment getAxeAssignment_1() { return cAxeAssignment_1; }
		
		//STRING
		public RuleCall getAxeSTRINGTerminalRuleCall_1_0() { return cAxeSTRINGTerminalRuleCall_1_0; }
		
		//'greater'
		public Keyword getGreaterKeyword_2() { return cGreaterKeyword_2; }
		
		//'than'
		public Keyword getThanKeyword_3() { return cThanKeyword_3; }
		
		//value=INT
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_4_0() { return cValueINTTerminalRuleCall_4_0; }
	}
	public class IsLowerThanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.IsLowerThan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIsLowerThanAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAxeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAxeSTRINGTerminalRuleCall_1_0 = (RuleCall)cAxeAssignment_1.eContents().get(0);
		private final Keyword cLowerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cThanKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueINTTerminalRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//IsLowerThan:
		//	{IsLowerThan} axe=STRING 'lower' 'than' value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//{IsLowerThan} axe=STRING 'lower' 'than' value=INT
		public Group getGroup() { return cGroup; }
		
		//{IsLowerThan}
		public Action getIsLowerThanAction_0() { return cIsLowerThanAction_0; }
		
		//axe=STRING
		public Assignment getAxeAssignment_1() { return cAxeAssignment_1; }
		
		//STRING
		public RuleCall getAxeSTRINGTerminalRuleCall_1_0() { return cAxeSTRINGTerminalRuleCall_1_0; }
		
		//'lower'
		public Keyword getLowerKeyword_2() { return cLowerKeyword_2; }
		
		//'than'
		public Keyword getThanKeyword_3() { return cThanKeyword_3; }
		
		//value=INT
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_4_0() { return cValueINTTerminalRuleCall_4_0; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.farmbot.MyFarmbot.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final FarmbotElements pFarmbot;
	private final InstructionElements pInstruction;
	private final CommandElements pCommand;
	private final SequenceCommandElements pSequenceCommand;
	private final SequenceInstructionElements pSequenceInstruction;
	private final BooleanExpressionElements pBooleanExpression;
	private final TurnOnElements pTurnOn;
	private final TurnOffElements pTurnOff;
	private final MoveRelativeElements pMoveRelative;
	private final FindHomeElements pFindHome;
	private final SequenceElements pSequence;
	private final IfElements pIf;
	private final MoveAbsoluteElements pMoveAbsolute;
	private final ExecuteSequenceElements pExecuteSequence;
	private final WaitElements pWait;
	private final IsToolOnElements pIsToolOn;
	private final SendMessageElements pSendMessage;
	private final RunFarmwareElements pRunFarmware;
	private final TakePhotoElements pTakePhoto;
	private final ScheduleElements pSchedule;
	private final ListPeripheralsElements pListPeripherals;
	private final ListSequencesElements pListSequences;
	private final IsEqualToElements pIsEqualTo;
	private final IsNotEqualToElements pIsNotEqualTo;
	private final IsGreaterThanElements pIsGreaterThan;
	private final IsLowerThanElements pIsLowerThan;
	private final EDoubleElements pEDouble;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyFarmbotGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFarmbot = new FarmbotElements();
		this.pInstruction = new InstructionElements();
		this.pCommand = new CommandElements();
		this.pSequenceCommand = new SequenceCommandElements();
		this.pSequenceInstruction = new SequenceInstructionElements();
		this.pBooleanExpression = new BooleanExpressionElements();
		this.pTurnOn = new TurnOnElements();
		this.pTurnOff = new TurnOffElements();
		this.pMoveRelative = new MoveRelativeElements();
		this.pFindHome = new FindHomeElements();
		this.pSequence = new SequenceElements();
		this.pIf = new IfElements();
		this.pMoveAbsolute = new MoveAbsoluteElements();
		this.pExecuteSequence = new ExecuteSequenceElements();
		this.pWait = new WaitElements();
		this.pIsToolOn = new IsToolOnElements();
		this.pSendMessage = new SendMessageElements();
		this.pRunFarmware = new RunFarmwareElements();
		this.pTakePhoto = new TakePhotoElements();
		this.pSchedule = new ScheduleElements();
		this.pListPeripherals = new ListPeripheralsElements();
		this.pListSequences = new ListSequencesElements();
		this.pIsEqualTo = new IsEqualToElements();
		this.pIsNotEqualTo = new IsNotEqualToElements();
		this.pIsGreaterThan = new IsGreaterThanElements();
		this.pIsLowerThan = new IsLowerThanElements();
		this.pEDouble = new EDoubleElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xtext.farmbot.MyFarmbot".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Farmbot:
	//	{Farmbot} instructions+=Instruction+;
	public FarmbotElements getFarmbotAccess() {
		return pFarmbot;
	}
	
	public ParserRule getFarmbotRule() {
		return getFarmbotAccess().getRule();
	}
	
	//Instruction:
	//	SequenceInstruction | Sequence | Command;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//Command:
	//	Schedule | ListPeripherals | ListSequences;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}
	
	//SequenceCommand:
	//	TurnOn | TurnOff | MoveRelative | FindHome | MoveAbsolute | ExecuteSequence | Wait | IsToolOn | SendMessage |
	//	RunFarmware | TakePhoto;
	public SequenceCommandElements getSequenceCommandAccess() {
		return pSequenceCommand;
	}
	
	public ParserRule getSequenceCommandRule() {
		return getSequenceCommandAccess().getRule();
	}
	
	//SequenceInstruction:
	//	If | SequenceCommand;
	public SequenceInstructionElements getSequenceInstructionAccess() {
		return pSequenceInstruction;
	}
	
	public ParserRule getSequenceInstructionRule() {
		return getSequenceInstructionAccess().getRule();
	}
	
	//BooleanExpression:
	//	IsToolOn | IsEqualTo | IsNotEqualTo | IsGreaterThan | IsLowerThan;
	public BooleanExpressionElements getBooleanExpressionAccess() {
		return pBooleanExpression;
	}
	
	public ParserRule getBooleanExpressionRule() {
		return getBooleanExpressionAccess().getRule();
	}
	
	//TurnOn:
	//	{TurnOn}
	//	'turnOn(' 'pin=' pin=INT ',' 'mode=' mode=STRING ')';
	public TurnOnElements getTurnOnAccess() {
		return pTurnOn;
	}
	
	public ParserRule getTurnOnRule() {
		return getTurnOnAccess().getRule();
	}
	
	//TurnOff:
	//	{TurnOff}
	//	'turnOff(' 'pin=' pin=INT ',' 'mode=' mode=STRING ')';
	public TurnOffElements getTurnOffAccess() {
		return pTurnOff;
	}
	
	public ParserRule getTurnOffRule() {
		return getTurnOffAccess().getRule();
	}
	
	//MoveRelative:
	//	{MoveRelative}
	//	'moveRelative(' 'x=' x=INT ',' 'y=' y=INT ',' 'z=' z=INT ',' 'speed=' speed=EDouble ')';
	public MoveRelativeElements getMoveRelativeAccess() {
		return pMoveRelative;
	}
	
	public ParserRule getMoveRelativeRule() {
		return getMoveRelativeAccess().getRule();
	}
	
	//FindHome:
	//	{FindHome}
	//	'findHome(' 'findX=' findX=EBoolean ',' 'findY=' findY=EBoolean ',' 'findZ=' findZ=EBoolean ')';
	public FindHomeElements getFindHomeAccess() {
		return pFindHome;
	}
	
	public ParserRule getFindHomeRule() {
		return getFindHomeAccess().getRule();
	}
	
	//Sequence:
	//	{Sequence}
	//	'sequence' name=STRING
	//	sequenceInstructions+=SequenceInstruction*
	//	'end';
	public SequenceElements getSequenceAccess() {
		return pSequence;
	}
	
	public ParserRule getSequenceRule() {
		return getSequenceAccess().getRule();
	}
	
	//If:
	//	{If}
	//	'if' booleanExpression=BooleanExpression
	//	'then' then=ExecuteSequence ('else' else=ExecuteSequence)?
	//	'end';
	public IfElements getIfAccess() {
		return pIf;
	}
	
	public ParserRule getIfRule() {
		return getIfAccess().getRule();
	}
	
	//MoveAbsolute:
	//	{MoveAbsolute}
	//	'moveAbsolute(' 'x=' x=INT ',' 'y=' y=INT ',' 'z=' z=INT ',' 'speed=' speed=EDouble ')';
	public MoveAbsoluteElements getMoveAbsoluteAccess() {
		return pMoveAbsolute;
	}
	
	public ParserRule getMoveAbsoluteRule() {
		return getMoveAbsoluteAccess().getRule();
	}
	
	//ExecuteSequence:
	//	{ExecuteSequence}
	//	'executeSequence' '(' 'id=' id=INT ')';
	public ExecuteSequenceElements getExecuteSequenceAccess() {
		return pExecuteSequence;
	}
	
	public ParserRule getExecuteSequenceRule() {
		return getExecuteSequenceAccess().getRule();
	}
	
	//Wait:
	//	{Wait}
	//	'wait' '(' 'duration=' duration=EDouble ')';
	public WaitElements getWaitAccess() {
		return pWait;
	}
	
	public ParserRule getWaitRule() {
		return getWaitAccess().getRule();
	}
	
	//IsToolOn:
	//	{IsToolOn}
	//	'isToolOn' '(' 'pin=' pin=INT ')';
	public IsToolOnElements getIsToolOnAccess() {
		return pIsToolOn;
	}
	
	public ParserRule getIsToolOnRule() {
		return getIsToolOnAccess().getRule();
	}
	
	//SendMessage:
	//	{SendMessage}
	//	'sendMessage' '(' 'message=' message=STRING ')';
	public SendMessageElements getSendMessageAccess() {
		return pSendMessage;
	}
	
	public ParserRule getSendMessageRule() {
		return getSendMessageAccess().getRule();
	}
	
	//RunFarmware:
	//	{RunFarmware}
	//	'runFarmware' '(' 'name=' name=STRING ')';
	public RunFarmwareElements getRunFarmwareAccess() {
		return pRunFarmware;
	}
	
	public ParserRule getRunFarmwareRule() {
		return getRunFarmwareAccess().getRule();
	}
	
	//TakePhoto:
	//	{TakePhoto}
	//	'takePhoto()';
	public TakePhotoElements getTakePhotoAccess() {
		return pTakePhoto;
	}
	
	public ParserRule getTakePhotoRule() {
		return getTakePhotoAccess().getRule();
	}
	
	//Schedule:
	//	{Schedule}
	//	'schedule' '(' 'sequence=' sequence=STRING ',' 'startDate=' startDate=STRING ',' 'startTime=' startTime=STRING ','
	//	'repeat=' repeat=EBoolean ',' 'repeatFrequency=' repeatFrequency=INT ',' 'repeatUnit=' repeatUnit=STRING ','
	//	'endDate=' endDate=STRING ',' 'endTime=' endTime=STRING ')';
	public ScheduleElements getScheduleAccess() {
		return pSchedule;
	}
	
	public ParserRule getScheduleRule() {
		return getScheduleAccess().getRule();
	}
	
	//ListPeripherals:
	//	{ListPeripherals}
	//	'listPeripherals()';
	public ListPeripheralsElements getListPeripheralsAccess() {
		return pListPeripherals;
	}
	
	public ParserRule getListPeripheralsRule() {
		return getListPeripheralsAccess().getRule();
	}
	
	//ListSequences:
	//	{ListSequences}
	//	'listSequences()';
	public ListSequencesElements getListSequencesAccess() {
		return pListSequences;
	}
	
	public ParserRule getListSequencesRule() {
		return getListSequencesAccess().getRule();
	}
	
	//IsEqualTo:
	//	{IsEqualTo} axe=STRING 'equals' 'to' value=INT;
	public IsEqualToElements getIsEqualToAccess() {
		return pIsEqualTo;
	}
	
	public ParserRule getIsEqualToRule() {
		return getIsEqualToAccess().getRule();
	}
	
	//IsNotEqualTo:
	//	{IsNotEqualTo} axe=STRING 'not' 'equals' 'to' value=INT;
	public IsNotEqualToElements getIsNotEqualToAccess() {
		return pIsNotEqualTo;
	}
	
	public ParserRule getIsNotEqualToRule() {
		return getIsNotEqualToAccess().getRule();
	}
	
	//IsGreaterThan:
	//	{IsGreaterThan} axe=STRING 'greater' 'than' value=INT;
	public IsGreaterThanElements getIsGreaterThanAccess() {
		return pIsGreaterThan;
	}
	
	public ParserRule getIsGreaterThanRule() {
		return getIsGreaterThanAccess().getRule();
	}
	
	//IsLowerThan:
	//	{IsLowerThan} axe=STRING 'lower' 'than' value=INT;
	public IsLowerThanElements getIsLowerThanAccess() {
		return pIsLowerThan;
	}
	
	public ParserRule getIsLowerThanRule() {
		return getIsLowerThanAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
