/**
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ui.contentassist;

import xtext.farmbot.ui.contentassist.AbstractMyFarmbotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyFarmbotProposalProvider extends AbstractMyFarmbotProposalProvider {
}
