/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.farmbot.ui.internal.FarmbotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyFarmbotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FarmbotActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FarmbotActivator activator = FarmbotActivator.getInstance();
		return activator != null ? activator.getInjector(FarmbotActivator.XTEXT_FARMBOT_MYFARMBOT) : null;
	}

}
