/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import xtext.farmbot.MyFarmbotRuntimeModule
import xtext.farmbot.MyFarmbotStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyFarmbotIdeSetup extends MyFarmbotStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyFarmbotRuntimeModule, new MyFarmbotIdeModule))
	}
	
}
