/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.farmbot.ui.internal.FarmbotActivator;

public class MyFarmbotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FarmbotActivator.getInstance().getInjector("xtext.farmbot.MyFarmbot");
	}

}
