/**
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.validation;

import xtext.farmbot.validation.AbstractMyFarmbotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyFarmbotValidator extends AbstractMyFarmbotValidator {
}
