/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyFarmbotStandaloneSetup extends MyFarmbotStandaloneSetupGenerated {

	def static void doSetup() {
		new MyFarmbotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
