/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MyFarmbotProposalProvider extends AbstractMyFarmbotProposalProvider {
}
