/*
 * generated by Xtext 2.15.0
 */
package xtext.farmbot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyFarmbotScopeProvider extends DelegatingScopeProvider {
}
